[package]
name = "buns"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

authors = ["Dekirisu <dekirisu@gmail.com>"]
description = "Define token patterns."
keywords = ["macro","utility"]
repository = "https://github.com/dekirisu/buns"
documentation = "https://docs.rs/buns"
